package com.inappstory.sdk.core.api;

public enum IASCallbackType {
    ERROR,
    SHOW_STORY,
    SHOW_IN_APP_MESSAGE,
    SHOW_SLIDE,
    LIKE_DISLIKE,
    FAVORITE,
    CLOSE_STORY,
    CLOSE_IN_APP_MESSAGE,
    IN_APP_MESSAGE_WIDGET,
    IN_APP_MESSAGE_LOAD,
    STORY_WIDGET,
    ONBOARDING,
    SINGLE,
    SHARE_ADDITIONAL,
    CLICK_SHARE,
    CALL_TO_ACTION,
    GAME_READER
}
