package com.inappstory.sdk.core.api;

public enum IASCallbackType {
    EXCEPTION,
    ERROR,
    SHOW_STORY,
    SHOW_SLIDE,
    LIKE_DISLIKE,
    FAVORITE,
    CLOSE_STORY,
    STORY_WIDGET,
    ONBOARDING,
    SINGLE,
    SHARE_ADDITIONAL,
    CLICK_SHARE,
    CALL_TO_ACTION,
    GAME_READER,

    SHOW_IN_APP_MESSAGE,
    CLOSE_IN_APP_MESSAGE,
    IN_APP_MESSAGE_WIDGET,
    IN_APP_MESSAGE_LOAD,

    SHOW_BANNER,
    BANNER_WIDGET,
    BANNER_LOAD,
    CLOSE_BANNER
}
